# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CVD19Stats' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CVD19Stats


pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Firestore'

  target 'CVD19StatsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CVD19StatsUITests' do
    # Pods for testing
  end

end

